<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_arqueo
* GENERATION DATE:  30.06.2018
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_arqueo.php
* FOR MYSQL TABLE:  arqueo
* FOR MYSQL DB:     gservices
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/
require_once("../conexion/Conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_arqueo
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_arqueo;   // KEY ATTR. WITH AUTOINCREMENT

var $id_venta;   // (normal Attribute)
var $ingreso_arriendo;   // (normal Attribute)
var $ingreso_lavado;   // (normal Attribute)
var $ingreso_otros;   // (normal Attribute)
var $ingreso_total;   // (normal Attribute)
var $ingreso_saldo;   // (normal Attribute)
var $egreso_compras;   // (normal Attribute)
var $egreso_otros;   // (normal Attribute)
var $egreso_total;   // (normal Attribute)
var $egrego_desc;   // (normal Attribute)
var $boleta_inicial;   // (normal Attribute)
var $boleta_final;   // (normal Attribute)
var $time_cierracaja;   // (normal Attribute)
var $turno_arqueo;   // (normal Attribute)
var $usuario_arqueo;   // (normal Attribute)
var $estado_arqueo;   // (normal Attribute)
var $log_arqueo;   // (normal Attribute)
var $obs_arqueo;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_arqueo()
{

$this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getid_arqueo()
{
return $this->id_arqueo;
}

function getid_venta()
{
return $this->id_venta;
}

function getingreso_arriendo()
{
return $this->ingreso_arriendo;
}

function getingreso_lavado()
{
return $this->ingreso_lavado;
}

function getingreso_otros()
{
return $this->ingreso_otros;
}

function getingreso_total()
{
return $this->ingreso_total;
}

function getingreso_saldo()
{
return $this->ingreso_saldo;
}

function getegreso_compras()
{
return $this->egreso_compras;
}

function getegreso_otros()
{
return $this->egreso_otros;
}

function getegreso_total()
{
return $this->egreso_total;
}

function getegrego_desc()
{
return $this->egrego_desc;
}

function getboleta_inicial()
{
return $this->boleta_inicial;
}

function getboleta_final()
{
return $this->boleta_final;
}

function gettime_cierracaja()
{
return $this->time_cierracaja;
}

function getturno_arqueo()
{
return $this->turno_arqueo;
}

function getusuario_arqueo()
{
return $this->usuario_arqueo;
}

function getestado_arqueo()
{
return $this->estado_arqueo;
}

function getlog_arqueo()
{
return $this->log_arqueo;
}

function getobs_arqueo()
{
return $this->obs_arqueo;
}

// **********************
// SETTER METHODS
// **********************


function setid_arqueo($val)
{
$this->id_arqueo =  $val;
}

function setid_venta($val)
{
$this->id_venta =  $val;
}

function setingreso_arriendo($val)
{
$this->ingreso_arriendo =  $val;
}

function setingreso_lavado($val)
{
$this->ingreso_lavado =  $val;
}

function setingreso_otros($val)
{
$this->ingreso_otros =  $val;
}

function setingreso_total($val)
{
$this->ingreso_total =  $val;
}

function setingreso_saldo($val)
{
$this->ingreso_saldo =  $val;
}

function setegreso_compras($val)
{
$this->egreso_compras =  $val;
}

function setegreso_otros($val)
{
$this->egreso_otros =  $val;
}

function setegreso_total($val)
{
$this->egreso_total =  $val;
}

function setegrego_desc($val)
{
$this->egrego_desc =  $val;
}

function setboleta_inicial($val)
{
$this->boleta_inicial =  $val;
}

function setboleta_final($val)
{
$this->boleta_final =  $val;
}

function settime_cierracaja($val)
{
$this->time_cierracaja =  $val;
}

function setturno_arqueo($val)
{
$this->turno_arqueo =  $val;
}

function setusuario_arqueo($val)
{
$this->usuario_arqueo =  $val;
}

function setestado_arqueo($val)
{
$this->estado_arqueo =  $val;
}

function setlog_arqueo($val)
{
$this->log_arqueo =  $val;
}

function setobs_arqueo($val)
{
$this->obs_arqueo =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************
function msogetarqueoxrut(){
    $usuario_arqueo = $this->getusuario_arqueo();
    $sql =  "SELECT * FROM arqueo WHERE usuario_arqueo = '$usuario_arqueo' and estado_arqueo = 1 order by id_arqueo desc limit 1 ;";
    $result =  $this->database->consulta($sql);
    $row = $this->database->fetch_array($result);
    $this->setturno_arqueo($row['turno_arqueo']);
    $this->setusuario_arqueo($row['usuario_arqueo']);
    $this->setestado_arqueo($row['estado_arqueo']);
    $this->setid_arqueo($row['id_arqueo']);
}
function msogetarqueoxid(){
    $id_arqueo = $this->getid_arqueo();
    $sql =  "SELECT * FROM arqueo WHERE id_arqueo = '$id_arqueo'";
   $result =  $this->database->consulta($sql);
    $row = $this->database->fetch_array($result);
   $this->setturno_arqueo($row['turno_arqueo']);
    $this->setusuario_arqueo($row['usuario_arqueo']);
    $this->setestado_arqueo($row['estado_arqueo']);
  $this->setid_venta($row['id_venta']);
}
function select($id)
{

$sql =  "SELECT * FROM arqueo WHERE id_arqueo = $id;";
$result =  $this->database->consulta($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id_arqueo = $row->id_arqueo;

$this->id_venta = $row->id_venta;

$this->ingreso_arriendo = $row->ingreso_arriendo;

$this->ingreso_lavado = $row->ingreso_lavado;

$this->ingreso_otros = $row->ingreso_otros;

$this->ingreso_total = $row->ingreso_total;

$this->ingreso_saldo = $row->ingreso_saldo;

$this->egreso_compras = $row->egreso_compras;

$this->egreso_otros = $row->egreso_otros;

$this->egreso_total = $row->egreso_total;

$this->egrego_desc = $row->egrego_desc;

$this->boleta_inicial = $row->boleta_inicial;

$this->boleta_final = $row->boleta_final;

$this->time_cierracaja = $row->time_cierracaja;

$this->turno_arqueo = $row->turno_arqueo;

$this->usuario_arqueo = $row->usuario_arqueo;

$this->estado_arqueo = $row->estado_arqueo;

$this->log_arqueo = $row->log_arqueo;

$this->obs_arqueo = $row->obs_arqueo;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM arqueo WHERE id_arqueo = $id;";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_arqueo = ""; // clear key for autoincrement

$sql = "INSERT INTO arqueo ( id_venta,ingreso_arriendo,ingreso_lavado,ingreso_otros,ingreso_total,ingreso_saldo,egreso_compras,egreso_otros,egreso_total,egrego_desc,boleta_inicial,boleta_final,time_cierracaja,turno_arqueo,usuario_arqueo,estado_arqueo,log_arqueo,obs_arqueo ) VALUES ( '$this->id_venta','$this->ingreso_arriendo','$this->ingreso_lavado','$this->ingreso_otros','$this->ingreso_total','$this->ingreso_saldo','$this->egreso_compras','$this->egreso_otros','$this->egreso_total','$this->egrego_desc','$this->boleta_inicial','$this->boleta_final','$this->time_cierracaja','$this->turno_arqueo','$this->usuario_arqueo','$this->estado_arqueo','$this->log_arqueo','$this->obs_arqueo' )";
$result = $this->database->consulta($sql);
$this->id_arqueo = mysql_insert_id();

}

// **********************
// UPDATE
// **********************
function updateestado()
{
$id_arqueo = $this->getid_arqueo();
$sql = " UPDATE arqueo SET estado_arqueo = '$this->estado_arqueo' WHERE id_arqueo = $id_arqueo ";

$result = $this->database->consulta($sql);



}

function update($id)
{



$sql = " UPDATE arqueo SET  id_venta = '$this->id_venta',ingreso_arriendo = '$this->ingreso_arriendo',ingreso_lavado = '$this->ingreso_lavado',ingreso_otros = '$this->ingreso_otros',ingreso_total = '$this->ingreso_total',ingreso_saldo = '$this->ingreso_saldo',egreso_compras = '$this->egreso_compras',egreso_otros = '$this->egreso_otros',egreso_total = '$this->egreso_total',egrego_desc = '$this->egrego_desc',boleta_inicial = '$this->boleta_inicial',boleta_final = '$this->boleta_final',time_cierracaja = '$this->time_cierracaja',turno_arqueo = '$this->turno_arqueo',usuario_arqueo = '$this->usuario_arqueo',estado_arqueo = '$this->estado_arqueo',log_arqueo = '$this->log_arqueo',obs_arqueo = '$this->obs_arqueo' WHERE id_arqueo = $id ";

$result = $this->database->consulta($sql);



}


} // class : end

?>