<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_servicio
* GENERATION DATE:  25.06.2018
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_servicio.php
* FOR MYSQL TABLE:  servicio
* FOR MYSQL DB:     gservices
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/Conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_servicio
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_servicio;   // KEY ATTR. WITH AUTOINCREMENT

var $id_categoria;   // (normal Attribute)
var $nombre_servicio;   // (normal Attribute)
var $descripcion_servicio;   // (normal Attribute)
var $estado_servicio;   // (normal Attribute)
var $tipo_vechiculo;   // (normal Attribute)
var $precio;   // (normal Attribute)
var $precio_dia;   // (normal Attribute)
var $precio_noche;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_servicio()
{

$this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getid_servicio()
{
return $this->id_servicio;
}

function getid_categoria()
{
return $this->id_categoria;
}

function getnombre_servicio()
{
return $this->nombre_servicio;
}

function getdescripcion_servicio()
{
return $this->descripcion_servicio;
}

function getestado_servicio()
{
return $this->estado_servicio;
}

function gettipo_vechiculo()
{
return $this->tipo_vechiculo;
}

function getprecio()
{
return $this->precio;
}

function getprecio_dia()
{
return $this->precio_dia;
}

function getprecio_noche()
{
return $this->precio_noche;
}

// **********************
// SETTER METHODS
// **********************


function setid_servicio($val)
{
$this->id_servicio =  $val;
}

function setid_categoria($val)
{
$this->id_categoria =  $val;
}

function setnombre_servicio($val)
{
$this->nombre_servicio =  $val;
}

function setdescripcion_servicio($val)
{
$this->descripcion_servicio =  $val;
}

function setestado_servicio($val)
{
$this->estado_servicio =  $val;
}

function settipo_vechiculo($val)
{
$this->tipo_vechiculo =  $val;
}

function setprecio($val)
{
$this->precio =  $val;
}

function setprecio_dia($val)
{
$this->precio_dia =  $val;
}

function setprecio_noche($val)
{
$this->precio_noche =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function msogetvalorservicioxvehiculo()
{
$tipo_vehiculo = $this->gettipo_vechiculo();
$sql =  "SELECT * FROM servicio WHERE tipo_vehiculo = $tipo_vehiculo;";
$result =  $this->database->consulta($sql);
$row = $this->database->fetch_array($result);


//$this->id_servicio = $row->id_servicio;

//$this->id_categoria = $row->id_categoria;

//$this->nombre_servicio = $row->nombre_servicio;

//$this->descripcion_servicio = $row->descripcion_servicio;

//$this->estado_servicio = $row->estado_servicio;

//$this->tipo_vechiculo = $row->tipo_vechiculo;

$this->setprecio($row['precio']);

$this->setprecio_dia($row['precio_dia']) ;

$this->setprecio_noche($row['precio_noche']);

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM servicio WHERE id_servicio = $id;";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_servicio = ""; // clear key for autoincrement

$sql = "INSERT INTO servicio ( id_categoria,nombre_servicio,descripcion_servicio,estado_servicio,tipo_vechiculo,precio,precio_dia,precio_noche ) VALUES ( '$this->id_categoria','$this->nombre_servicio','$this->descripcion_servicio','$this->estado_servicio','$this->tipo_vechiculo','$this->precio','$this->precio_dia','$this->precio_noche' )";
$result = $this->database->consulta($sql);
$this->id_servicio = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE servicio SET  id_categoria = '$this->id_categoria',nombre_servicio = '$this->nombre_servicio',descripcion_servicio = '$this->descripcion_servicio',estado_servicio = '$this->estado_servicio',tipo_vechiculo = '$this->tipo_vechiculo',precio = '$this->precio',precio_dia = '$this->precio_dia',precio_noche = '$this->precio_noche' WHERE id_servicio = $id ";

$result = $this->database->consulta($sql);



}


} // class : end

?>