<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_punto_venta
* GENERATION DATE:  29.06.2018
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_punto_venta.php
* FOR MYSQL TABLE:  punto_venta
* FOR MYSQL DB:     gservices
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/Conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_punto_venta
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_venta;   // KEY ATTR. WITH AUTOINCREMENT

var $rut_usuario;   // (normal Attribute)
var $caja_inicial;   // (normal Attribute)
var $fecha_venta;   // (normal Attribute)
var $turno;   // (normal Attribute)
var $estado_venta;   // (normal Attribute)
var $venta_total;   // (normal Attribute)
var $caja_final;   // (normal Attribute)
var $observacion_venta;   // (normal Attribute)
var $time_abrecaja;   // (normal Attribute)
var $ip_caja;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_punto_venta()
{

$this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getid_venta()
{
return $this->id_venta;
}

function getrut_usuario()
{
return $this->rut_usuario;
}

function getcaja_inicial()
{
return $this->caja_inicial;
}

function getfecha_venta()
{
return $this->fecha_venta;
}

function getturno()
{
return $this->turno;
}

function getestado_venta()
{
return $this->estado_venta;
}

function getventa_total()
{
return $this->venta_total;
}

function getcaja_final()
{
return $this->caja_final;
}

function getobservacion_venta()
{
return $this->observacion_venta;
}

function gettime_abrecaja()
{
return $this->time_abrecaja;
}

function getip_caja()
{
return $this->ip_caja;
}

// **********************
// SETTER METHODS
// **********************


function setid_venta($val)
{
$this->id_venta =  $val;
}

function setrut_usuario($val)
{
$this->rut_usuario =  $val;
}

function setcaja_inicial($val)
{
$this->caja_inicial =  $val;
}

function setfecha_venta($val)
{
$this->fecha_venta =  $val;
}

function setturno($val)
{
$this->turno =  $val;
}

function setestado_venta($val)
{
$this->estado_venta =  $val;
}

function setventa_total($val)
{
$this->venta_total =  $val;
}

function setcaja_final($val)
{
$this->caja_final =  $val;
}

function setobservacion_venta($val)
{
$this->observacion_venta =  $val;
}

function settime_abrecaja($val)
{
$this->time_abrecaja =  $val;
}

function setip_caja($val)
{
$this->ip_caja =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************
function msoobpuntoventaxestadoyfecha(){
    $fecha_venta = $this->getfecha_venta();
    $sql =  "SELECT * FROM punto_venta WHERE  fecha_venta = '$fecha_venta' order by time_abrecaja desc limit 1";
$result =  $this->database->consulta($sql);

$row = $this->database->fetch_array($result);
$this->setid_venta($row['id_venta']);
$this->setestado_venta($row['estado_venta']);
}
function msoobpuntoventaxestado(){
    $sql =  "SELECT * FROM punto_venta WHERE estado_venta = 1 order by time_abrecaja desc limit 1";
$result =  $this->database->consulta($sql);

$row = $this->database->fetch_array($result);
$this->setid_venta($row['id_venta']);
}
function msoobpuntoventaxid(){
    $id_venta = $this->getid_venta();
    $sql =  "SELECT * FROM punto_venta WHERE  id_venta = '$id_venta'";
$result =  $this->database->consulta($sql);

$row = $this->database->fetch_array($result);
$this->setid_venta($row['id_venta']);
$this->setestado_venta($row['estado_venta']);
}

function select($id)
{

$sql =  "SELECT * FROM punto_venta WHERE id_venta = $id;";
$result =  $this->database->consulta($sql);

$row = mysql_fetch_object($result);


$this->id_venta = $row->id_venta;

$this->rut_usuario = $row->rut_usuario;

$this->caja_inicial = $row->caja_inicial;

$this->fecha_venta = $row->fecha_venta;

$this->turno = $row->turno;

$this->estado_venta = $row->estado_venta;

$this->venta_total = $row->venta_total;

$this->caja_final = $row->caja_final;

$this->observacion_venta = $row->observacion_venta;

$this->time_abrecaja = $row->time_abrecaja;

$this->ip_caja = $row->ip_caja;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM punto_venta WHERE id_venta = $id;";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_venta = ""; // clear key for autoincrement

$sql = "INSERT INTO punto_venta ( rut_usuario,caja_inicial,fecha_venta,turno,estado_venta,venta_total,caja_final,"
        . "observacion_venta,ip_caja ) "
        . "VALUES ( '$this->rut_usuario','$this->caja_inicial','$this->fecha_venta','$this->turno','$this->estado_venta',"
        . "'$this->venta_total','$this->caja_final','$this->observacion_venta','$this->ip_caja' )";
$result = $this->database->consulta($sql);
$this->id_venta = mysql_insert_id();

}

// **********************
// UPDATE
// **********************
function updatecierre()
{
$id_venta = $this->getid_venta();
$sql = " UPDATE punto_venta SET  estado_venta = '$this->estado_venta' WHERE id_venta = $id_venta ";

$result = $this->database->consulta($sql);



}

function update()
{

$sql = " UPDATE punto_venta SET  rut_usuario = '$this->rut_usuario',caja_inicial = '$this->caja_inicial',fecha_venta = '$this->fecha_venta',turno = '$this->turno',estado_venta = '$this->estado_venta',venta_total = '$this->venta_total',caja_final = '$this->caja_final',observacion_venta = '$this->observacion_venta',time_abrecaja = '$this->time_abrecaja',ip_caja = '$this->ip_caja' WHERE id_venta = $id ";

$result = $this->database->consulta($sql);



}


} // class : end

?>