<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_detalle_venta
* GENERATION DATE:  19.06.2018
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_detalle_venta.php
* FOR MYSQL TABLE:  detalle_venta
* FOR MYSQL DB:     gservices
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/Conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_detalle_venta
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_dventa;   // KEY ATTR. WITH AUTOINCREMENT

var $patente;   // (normal Attribute)
var $id_arqueo;   // (normal Attribute)
var $correlativo_venta;   // (normal Attribute)
var $tipo_servicio;   // (normal Attribute)
var $tipo_catvehiculo;   // (normal Attribute)
var $venta;   // (normal Attribute)
var $time_llegada;   // (normal Attribute)
var $time_salida;   // (normal Attribute)
var $time_registro;   // (normal Attribute)
var $time_cantidad;   // (normal Attribute)
var $estado_detalle;   // (normal Attribute)
var $estado_pagado;   // (normal Attribute)
var $observacion_detalle;   // (normal Attribute)
var $ubic_tablero;   // (normal Attribute)
var $saldo_venta;
var $turno_venta;
var $desc_venta;
var $arrdventa;
var $total_venta;

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_detalle_venta()
{

$this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getid_dventa()
{
return $this->id_dventa;
}

function getpatente()
{
return $this->patente;
}

function getid_arqueo()
{
return $this->id_arqueo;
}

function getcorrelativo_venta()
{
return $this->correlativo_venta;
}

function gettipo_servicio()
{
return $this->tipo_servicio;
}

function gettipo_catvehiculo()
{
return $this->tipo_catvehiculo;
}

function getventa()
{
return $this->venta;
}
function gettotal_venta()
{
return $this->total_venta;
}

function gettime_llegada()
{
return $this->time_llegada;
}

function gettime_salida()
{
return $this->time_salida;
}

function gettime_registro()
{
return $this->time_registro;
}

function gettime_cantidad()
{
return $this->time_cantidad;
}

function getestado_detalle()
{
return $this->estado_detalle;
}

function getestado_pagado()
{
return $this->estado_pagado;
}

function getobservacion_detalle()
{
return $this->observacion_detalle;
}

function getubic_tablero()
{
return $this->ubic_tablero;
}

function getsaldo_venta()
{
return $this->saldo_venta;
}
function getturno_venta()
{
return $this->turno_venta;
}
function getdesc_venta()
{
return $this->desc_venta;
}
// **********************
// SETTER METHODS
// **********************


function setid_dventa($val)
{
$this->id_dventa =  $val;
}

function setpatente($val)
{
$this->patente =  $val;
}

function setid_arqueo($val)
{
$this->id_arqueo =  $val;
}


function setcorrelativo_venta($val)
{
$this->correlativo_venta =  $val;
}

function settipo_servicio($val)
{
$this->tipo_servicio =  $val;
}

function settipo_catvehiculo($val)
{
$this->tipo_catvehiculo =  $val;
}

function setventa($val)
{
$this->venta =  $val;
}
function settotal_venta($val)
{
$this->total_venta =  $val;
}

function settime_llegada($val)
{
$this->time_llegada =  $val;
}

function settime_salida($val)
{
$this->time_salida =  $val;
}

function settime_registro($val)
{
$this->time_registro =  $val;
}

function settime_cantidad($val)
{
$this->time_cantidad =  $val;
}

function setestado_detalle($val)
{
$this->estado_detalle =  $val;
}

function setestado_pagado($val)
{
$this->estado_pagado =  $val;
}

function setobservacion_detalle($val)
{
$this->observacion_detalle =  $val;
}

function setubic_tablero($val)
{
$this->ubic_tablero =  $val;
}
function setsaldo_venta($val)
{
$this->saldo_venta =  $val;
}
function setturno_venta($val)
{
$this->turno_venta =  $val;
}
function setdesc_venta($val)
{
$this->desc_venta =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function msoobtsumaventaxid(){
$id_arqueo = $this->getid_arqueo();    
if($id_arqueo != ""){
$sql =  "SELECT SUM(venta) as total_venta FROM detalle_venta WHERE turno_venta = '$id_arqueo'";
$result =  $this->database->consulta($sql);
//$row = mysql_fetch_object($result);
$row = $this->database->fetch_array($result);
if($row['total_venta'] != "")
    $this->settotal_venta($row['total_venta']);
else 
    $this->settotal_venta("0");
}else
    $this->settotal_venta("0");
    
}

function msoobtenerregistroxid(){
$id_dventa = $this->getid_dventa();    
$sql =  "SELECT * FROM detalle_venta WHERE id_dventa = $id_dventa;";

$result =  $this->database->consulta($sql);
//$row = mysql_fetch_object($result);
$row = $this->database->fetch_array($result);
$this->arrdventa[$i]['time_llegada'] = $row['time_llegada'];
$this->settime_llegada($row['time_llegada']);
$this->settipo_servicio($row['tipo_servicio']);
$this->settipo_catvehiculo($row['tipo_catvehiculo']);

    
}
function msolistdetventa(){
//$id_dventa = $this->getid_dventa();    
$sql =  "SELECT * FROM detalle_venta ";
$result =  $this->database->consulta($sql);

$row = $this->database->fetch_array($result);


$i=0;
    while($row = $this->database->fetch_array($result)){
/*
$this->arrdventa[$i] = array('id_dventa' => $row['id_dventa'],'patente' => $row['patente'],
    'correlativo_venta' => $row['correlativo_venta'],'tipo_servicio' => $row['tipo_servicio'],
    'tipo_catvehiculo' => $row['tipo_catvehiculo'],'venta' =>$row['venta'] ,'time_llegada' =>$row['time_llegada'] ,
    'time_salida' => $row['time_salida'],'time_cantidad' => $row['time_cantidad'],
    'estado_detalle' => $row['estado_pago'],'observacion_detalle' => $row['observacion_detalle'],
    'ubic_tablero' => $row['ubic_tablero'],'saldo_venta' => $row['saldo_venta'],'turno_venta' =>  $row['turno_venta'],
    'desc_venta' => $row['desc_venta']);        
 */
   $this->arrdventa[$i]['id_dventa'] = $row['id_dventa'];
   $this->arrdventa[$i]['patente'] = $row['patente'];
   $this->arrdventa[$i]['correlativo_venta'] = $row['correlativo_venta'];
   $this->arrdventa[$i]['tipo_servicio'] = $row['tipo_servicio'];
   $this->arrdventa[$i]['tipo_catvehiculo'] = $row['tipo_catvehiculo'];
   $this->arrdventa[$i]['venta'] = $row['venta'];
   $this->arrdventa[$i]['time_llegada'] = $row['time_llegada'];
   $this->arrdventa[$i]['time_salida'] = $row['time_salida'];
   $this->arrdventa[$i]['time_cantidad'] = $row['time_cantidad'];
   $this->arrdventa[$i]['estado_detalle'] = $row['estado_detalle'];
   $this->arrdventa[$i]['estado_pagado'] = $row['estado_pagado'];
   $this->arrdventa[$i]['observacion_detalle'] = $row['observacion_detalle'];
   $this->arrdventa[$i]['ubic_tablero'] = $row['ubic_tablero'];
   $this->arrdventa[$i]['saldo_venta'] = $row['saldo_venta'];
   $this->arrdventa[$i]['turno_venta'] = $row['turno_venta'];
   $this->arrdventa[$i]['desc_venta'] = $row['desc_venta'];
 

  // $this->arrdventa[$i][''] = $row[''];
   
   $i++;
    }
    
}

function select($id)
{

$sql =  "SELECT * FROM detalle_venta WHERE id_dventa = $id;";
$result =  $this->database->consulta($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id_dventa = $row->id_dventa;

$this->patente = $row->patente;

//$this->id_arqueo = $row->id_arqueo;

//$this->correlativo_venta = $row->correlativo_venta;

$this->tipo_servicio = $row->tipo_servicio;

$this->tipo_catvehiculo = $row->tipo_catvehiculo;

//$this->venta = $row->venta;

$this->time_llegada = $row->time_llegada;

//$this->time_salida = $row->time_salida;

//$this->time_registro = $row->time_registro;

//$this->time_cantidad = $row->time_cantidad;

//$this->estado_detalle = $row->estado_detalle;

$this->estado_pagado = $row->estado_pagado;

//$this->observacion_detalle = $row->observacion_detalle;

$this->ubic_tablero = $row->ubic_tablero;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM detalle_venta WHERE id_dventa = $id;";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_dventa = ""; // clear key for autoincrement

$sql = "INSERT INTO detalle_venta ( patente,id_arqueo,correlativo_venta,tipo_servicio,tipo_catvehiculo,venta,time_llegada,time_salida,time_cantidad,estado_detalle,estado_pagado,observacion_detalle,ubic_tablero ) VALUES ( '$this->patente','$this->id_arqueo','$this->correlativo_venta','$this->tipo_servicio','$this->tipo_catvehiculo','$this->venta','$this->time_llegada','$this->time_salida','$this->time_cantidad','$this->estado_detalle','$this->estado_pagado','$this->observacion_detalle','$this->ubic_tablero' )";
$result = $this->database->consulta($sql);
$this->id_dventa = mysql_insert_id();

}

// **********************
// UPDATE
// **********************
function updateingreso()
{
$id_dventa = $this->getid_dventa();
$sql = " UPDATE detalle_venta SET  patente = '$this->patente',tipo_servicio = '$this->tipo_servicio',"
        . "tipo_catvehiculo = '$this->tipo_catvehiculo' WHERE id_dventa = $id_dventa ";

$result = $this->database->consulta($sql);

}
function updatepago()
{
$id_dventa = $this->getid_dventa();
$sql = " UPDATE detalle_venta SET venta = '$this->venta',time_salida = '$this->time_salida',"
        . "time_cantidad = '$this->time_cantidad',estado_detalle = '$this->estado_detalle',estado_pagado = '$this->estado_pagado',"
        . "turno_venta = '$this->turno_venta' WHERE id_dventa = $id_dventa ";

$result = $this->database->consulta($sql);

}

function updateestado()
{
$id_dventa = $this->getid_dventa();
$sql = " UPDATE detalle_venta SET estado_detalle = '$this->estado_detalle',"
        . "turno_venta = '$this->turno_venta' WHERE id_dventa = $id_dventa ";

$result = $this->database->consulta($sql);

}

function update($id)
{

$sql = " UPDATE detalle_venta SET  patente = '$this->patente',id_arqueo = '$this->id_arqueo',correlativo_venta = '$this->correlativo_venta',tipo_servicio = '$this->tipo_servicio',tipo_catvehiculo = '$this->tipo_catvehiculo',venta = '$this->venta',time_llegada = '$this->time_llegada',time_salida = '$this->time_salida',time_registro = '$this->time_registro',time_cantidad = '$this->time_cantidad',estado_detalle = '$this->estado_detalle',estado_pagado = '$this->estado_pagado',observacion_detalle = '$this->observacion_detalle',ubic_tablero = '$this->ubic_tablero' WHERE id_dventa = $id ";

$result = $this->database->consulta($sql);

}


} // class : end

?>